/*
 * This file is part of the JavaRock ViaBedrock compatibility patch.
 * Copyright (C) 2023-2026 RK_01/RaphiMC, JavaRock contributors, and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Generated by scripts/generate-viabedrock-rendering-data.cjs from
 * minecraft-data Java 1.21.11. Do not edit by hand.
 */
package net.raphimc.viabedrock.protocol.storage;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

final class BridgeBlockRenderingData {

    private static final String ZERO_FILTER_DATA =
            "acacia_button acacia_door acacia_fence acacia_fence_gate acacia_hanging_sign acacia_pressure_plate" +
            "acacia_sapling acacia_shelf acacia_sign acacia_slab acacia_stairs acacia_trapdoor acacia_wall_hanging_sign" +
            "acacia_wall_sign activator_rail air allium amethyst_cluster andesite_slab andesite_stairs andesite_wall anvil" +
            "attached_melon_stem attached_pumpkin_stem azalea azure_bluet bamboo bamboo_button bamboo_door bamboo_fence" +
            "bamboo_fence_gate bamboo_hanging_sign bamboo_mosaic_slab bamboo_mosaic_stairs bamboo_pressure_plate" +
            "bamboo_sapling bamboo_shelf bamboo_sign bamboo_slab bamboo_stairs bamboo_trapdoor bamboo_wall_hanging_sign" +
            "bamboo_wall_sign barrier beetroots bell big_dripleaf big_dripleaf_stem birch_button birch_door birch_fence" +
            "birch_fence_gate birch_hanging_sign birch_pressure_plate birch_sapling birch_shelf birch_sign birch_slab" +
            "birch_stairs birch_trapdoor birch_wall_hanging_sign birch_wall_sign black_banner black_bed black_candle" +
            "black_candle_cake black_carpet black_stained_glass black_stained_glass_pane black_wall_banner blackstone_slab" +
            "blackstone_stairs blackstone_wall blue_banner blue_bed blue_candle blue_candle_cake blue_carpet blue_orchid" +
            "blue_stained_glass blue_stained_glass_pane blue_wall_banner brewing_stand brick_slab brick_stairs brick_wall" +
            "brown_banner brown_bed brown_candle brown_candle_cake brown_carpet brown_mushroom brown_stained_glass" +
            "brown_stained_glass_pane brown_wall_banner bush cactus cactus_flower cake calibrated_sculk_sensor campfire" +
            "candle candle_cake carrots cauldron cave_air cave_vines cave_vines_plant cherry_button cherry_door" +
            "cherry_fence cherry_fence_gate cherry_hanging_sign cherry_pressure_plate cherry_sapling cherry_shelf" +
            "cherry_sign cherry_slab cherry_stairs cherry_trapdoor cherry_wall_hanging_sign cherry_wall_sign chest" +
            "chipped_anvil closed_eyeblossom cobbled_deepslate_slab cobbled_deepslate_stairs cobbled_deepslate_wall" +
            "cobblestone_slab cobblestone_stairs cobblestone_wall cocoa comparator composter copper_bars copper_chain" +
            "copper_chest copper_door copper_golem_statue copper_grate copper_lantern copper_torch copper_trapdoor" +
            "copper_wall_torch cornflower creeper_head creeper_wall_head crimson_button crimson_door crimson_fence" +
            "crimson_fence_gate crimson_fungus crimson_hanging_sign crimson_pressure_plate crimson_roots crimson_shelf" +
            "crimson_sign crimson_slab crimson_stairs crimson_trapdoor crimson_wall_hanging_sign crimson_wall_sign" +
            "cut_copper_slab cut_copper_stairs cut_red_sandstone_slab cut_sandstone_slab cyan_banner cyan_bed cyan_candle" +
            "cyan_candle_cake cyan_carpet cyan_stained_glass cyan_stained_glass_pane cyan_wall_banner damaged_anvil" +
            "dandelion dark_oak_button dark_oak_door dark_oak_fence dark_oak_fence_gate dark_oak_hanging_sign" +
            "dark_oak_pressure_plate dark_oak_sapling dark_oak_shelf dark_oak_sign dark_oak_slab dark_oak_stairs" +
            "dark_oak_trapdoor dark_oak_wall_hanging_sign dark_oak_wall_sign dark_prismarine_slab dark_prismarine_stairs" +
            "daylight_detector dead_bush decorated_pot deepslate_brick_slab deepslate_brick_stairs deepslate_brick_wall" +
            "deepslate_tile_slab deepslate_tile_stairs deepslate_tile_wall detector_rail diorite_slab diorite_stairs" +
            "diorite_wall dirt_path dragon_egg dragon_head dragon_wall_head dried_ghast enchanting_table end_portal" +
            "end_portal_frame end_rod end_stone_brick_slab end_stone_brick_stairs end_stone_brick_wall ender_chest" +
            "exposed_copper_bars exposed_copper_chain exposed_copper_chest exposed_copper_door exposed_copper_golem_statue" +
            "exposed_copper_grate exposed_copper_lantern exposed_copper_trapdoor exposed_cut_copper_slab" +
            "exposed_cut_copper_stairs exposed_lightning_rod farmland fern fire firefly_bush flower_pot flowering_azalea" +
            "frogspawn glass glass_pane glow_lichen golden_dandelion granite_slab granite_stairs granite_wall gray_banner" +
            "gray_bed gray_candle gray_candle_cake gray_carpet gray_stained_glass gray_stained_glass_pane gray_wall_banner" +
            "green_banner green_bed green_candle green_candle_cake green_carpet green_stained_glass" +
            "green_stained_glass_pane green_wall_banner grindstone hanging_roots heavy_core heavy_weighted_pressure_plate" +
            "hopper iron_bars iron_chain iron_door iron_trapdoor jungle_button jungle_door jungle_fence jungle_fence_gate" +
            "jungle_hanging_sign jungle_pressure_plate jungle_sapling jungle_shelf jungle_sign jungle_slab jungle_stairs" +
            "jungle_trapdoor jungle_wall_hanging_sign jungle_wall_sign ladder lantern large_amethyst_bud large_fern" +
            "lava_cauldron leaf_litter lectern lever light light_blue_banner light_blue_bed light_blue_candle" +
            "light_blue_candle_cake light_blue_carpet light_blue_stained_glass light_blue_stained_glass_pane" +
            "light_blue_wall_banner light_gray_banner light_gray_bed light_gray_candle light_gray_candle_cake" +
            "light_gray_carpet light_gray_stained_glass light_gray_stained_glass_pane light_gray_wall_banner" +
            "light_weighted_pressure_plate lightning_rod lilac lily_of_the_valley lily_pad lime_banner lime_bed lime_candle" +
            "lime_candle_cake lime_carpet lime_stained_glass lime_stained_glass_pane lime_wall_banner magenta_banner" +
            "magenta_bed magenta_candle magenta_candle_cake magenta_carpet magenta_stained_glass magenta_stained_glass_pane" +
            "magenta_wall_banner mangrove_button mangrove_door mangrove_fence mangrove_fence_gate mangrove_hanging_sign" +
            "mangrove_pressure_plate mangrove_propagule mangrove_shelf mangrove_sign mangrove_slab mangrove_stairs" +
            "mangrove_trapdoor mangrove_wall_hanging_sign mangrove_wall_sign medium_amethyst_bud melon_stem moss_carpet" +
            "mossy_cobblestone_slab mossy_cobblestone_stairs mossy_cobblestone_wall mossy_stone_brick_slab" +
            "mossy_stone_brick_stairs mossy_stone_brick_wall moving_piston mud_brick_slab mud_brick_stairs mud_brick_wall" +
            "nether_brick_fence nether_brick_slab nether_brick_stairs nether_brick_wall nether_portal nether_sprouts" +
            "nether_wart oak_button oak_door oak_fence oak_fence_gate oak_hanging_sign oak_pressure_plate oak_sapling" +
            "oak_shelf oak_sign oak_slab oak_stairs oak_trapdoor oak_wall_hanging_sign oak_wall_sign open_eyeblossom" +
            "orange_banner orange_bed orange_candle orange_candle_cake orange_carpet orange_stained_glass" +
            "orange_stained_glass_pane orange_tulip orange_wall_banner oxeye_daisy oxidized_copper_bars" +
            "oxidized_copper_chain oxidized_copper_chest oxidized_copper_door oxidized_copper_golem_statue" +
            "oxidized_copper_grate oxidized_copper_lantern oxidized_copper_trapdoor oxidized_cut_copper_slab" +
            "oxidized_cut_copper_stairs oxidized_lightning_rod pale_hanging_moss pale_moss_carpet pale_oak_button" +
            "pale_oak_door pale_oak_fence pale_oak_fence_gate pale_oak_hanging_sign pale_oak_pressure_plate" +
            "pale_oak_sapling pale_oak_shelf pale_oak_sign pale_oak_slab pale_oak_stairs pale_oak_trapdoor" +
            "pale_oak_wall_hanging_sign pale_oak_wall_sign peony petrified_oak_slab piglin_head piglin_wall_head" +
            "pink_banner pink_bed pink_candle pink_candle_cake pink_carpet pink_petals pink_stained_glass" +
            "pink_stained_glass_pane pink_tulip pink_wall_banner piston_head pitcher_crop pitcher_plant player_head" +
            "player_wall_head pointed_dripstone polished_andesite_slab polished_andesite_stairs" +
            "polished_blackstone_brick_slab polished_blackstone_brick_stairs polished_blackstone_brick_wall" +
            "polished_blackstone_button polished_blackstone_pressure_plate polished_blackstone_slab" +
            "polished_blackstone_stairs polished_blackstone_wall polished_deepslate_slab polished_deepslate_stairs" +
            "polished_deepslate_wall polished_diorite_slab polished_diorite_stairs polished_granite_slab" +
            "polished_granite_stairs polished_tuff_slab polished_tuff_stairs polished_tuff_wall poppy potatoes" +
            "potted_acacia_sapling potted_allium potted_azalea_bush potted_azure_bluet potted_bamboo potted_birch_sapling" +
            "potted_blue_orchid potted_brown_mushroom potted_cactus potted_cherry_sapling potted_closed_eyeblossom" +
            "potted_cornflower potted_crimson_fungus potted_crimson_roots potted_dandelion potted_dark_oak_sapling" +
            "potted_dead_bush potted_fern potted_flowering_azalea_bush potted_golden_dandelion potted_jungle_sapling" +
            "potted_lily_of_the_valley potted_mangrove_propagule potted_oak_sapling potted_open_eyeblossom" +
            "potted_orange_tulip potted_oxeye_daisy potted_pale_oak_sapling potted_pink_tulip potted_poppy" +
            "potted_red_mushroom potted_red_tulip potted_spruce_sapling potted_torchflower potted_warped_fungus" +
            "potted_warped_roots potted_white_tulip potted_wither_rose powder_snow_cauldron powered_rail" +
            "prismarine_brick_slab prismarine_brick_stairs prismarine_slab prismarine_stairs prismarine_wall pumpkin_stem" +
            "purple_banner purple_bed purple_candle purple_candle_cake purple_carpet purple_stained_glass" +
            "purple_stained_glass_pane purple_wall_banner purpur_slab purpur_stairs quartz_slab quartz_stairs rail" +
            "red_banner red_bed red_candle red_candle_cake red_carpet red_mushroom red_nether_brick_slab" +
            "red_nether_brick_stairs red_nether_brick_wall red_sandstone_slab red_sandstone_stairs red_sandstone_wall" +
            "red_stained_glass red_stained_glass_pane red_tulip red_wall_banner redstone_torch redstone_wall_torch" +
            "redstone_wire repeater resin_brick_slab resin_brick_stairs resin_brick_wall rose_bush sandstone_slab" +
            "sandstone_stairs sandstone_wall scaffolding sculk_sensor short_dry_grass short_grass skeleton_skull" +
            "skeleton_wall_skull small_amethyst_bud small_dripleaf smooth_quartz_slab smooth_quartz_stairs" +
            "smooth_red_sandstone_slab smooth_red_sandstone_stairs smooth_sandstone_slab smooth_sandstone_stairs" +
            "smooth_stone_slab sniffer_egg snow soul_campfire soul_fire soul_lantern soul_torch soul_wall_torch" +
            "spore_blossom spruce_button spruce_door spruce_fence spruce_fence_gate spruce_hanging_sign" +
            "spruce_pressure_plate spruce_sapling spruce_shelf spruce_sign spruce_slab spruce_stairs spruce_trapdoor" +
            "spruce_wall_hanging_sign spruce_wall_sign stone_brick_slab stone_brick_stairs stone_brick_wall stone_button" +
            "stone_pressure_plate stone_slab stone_stairs stonecutter structure_void sugar_cane sunflower sweet_berry_bush" +
            "tall_dry_grass tall_grass torch torchflower torchflower_crop trapped_chest tripwire tripwire_hook" +
            "tuff_brick_slab tuff_brick_stairs tuff_brick_wall tuff_slab tuff_stairs tuff_wall turtle_egg twisting_vines" +
            "twisting_vines_plant vine void_air wall_torch warped_button warped_door warped_fence warped_fence_gate" +
            "warped_fungus warped_hanging_sign warped_pressure_plate warped_roots warped_shelf warped_sign warped_slab" +
            "warped_stairs warped_trapdoor warped_wall_hanging_sign warped_wall_sign water_cauldron waxed_copper_bars" +
            "waxed_copper_chain waxed_copper_chest waxed_copper_door waxed_copper_golem_statue waxed_copper_grate" +
            "waxed_copper_lantern waxed_copper_trapdoor waxed_cut_copper_slab waxed_cut_copper_stairs" +
            "waxed_exposed_copper_bars waxed_exposed_copper_chain waxed_exposed_copper_chest waxed_exposed_copper_door" +
            "waxed_exposed_copper_golem_statue waxed_exposed_copper_grate waxed_exposed_copper_lantern" +
            "waxed_exposed_copper_trapdoor waxed_exposed_cut_copper_slab waxed_exposed_cut_copper_stairs" +
            "waxed_exposed_lightning_rod waxed_lightning_rod waxed_oxidized_copper_bars waxed_oxidized_copper_chain" +
            "waxed_oxidized_copper_chest waxed_oxidized_copper_door waxed_oxidized_copper_golem_statue" +
            "waxed_oxidized_copper_grate waxed_oxidized_copper_lantern waxed_oxidized_copper_trapdoor" +
            "waxed_oxidized_cut_copper_slab waxed_oxidized_cut_copper_stairs waxed_oxidized_lightning_rod" +
            "waxed_weathered_copper_bars waxed_weathered_copper_chain waxed_weathered_copper_chest" +
            "waxed_weathered_copper_door waxed_weathered_copper_golem_statue waxed_weathered_copper_grate" +
            "waxed_weathered_copper_lantern waxed_weathered_copper_trapdoor waxed_weathered_cut_copper_slab" +
            "waxed_weathered_cut_copper_stairs waxed_weathered_lightning_rod weathered_copper_bars weathered_copper_chain" +
            "weathered_copper_chest weathered_copper_door weathered_copper_golem_statue weathered_copper_grate" +
            "weathered_copper_lantern weathered_copper_trapdoor weathered_cut_copper_slab weathered_cut_copper_stairs" +
            "weathered_lightning_rod weeping_vines weeping_vines_plant wheat white_banner white_bed white_candle" +
            "white_candle_cake white_carpet white_stained_glass white_stained_glass_pane white_tulip white_wall_banner" +
            "wildflowers wither_rose wither_skeleton_skull wither_skeleton_wall_skull yellow_banner yellow_bed" +
            "yellow_candle yellow_candle_cake yellow_carpet yellow_stained_glass yellow_stained_glass_pane" +
            "yellow_wall_banner zombie_head zombie_wall_head";
    private static final String PARTIAL_FILTER_DATA =
            "acacia_leaves=1 azalea_leaves=1 beacon=1 birch_leaves=1 black_shulker_box=1 blue_shulker_box=1 brain_coral=1" +
            "brain_coral_fan=1 brain_coral_wall_fan=1 brown_shulker_box=1 bubble_column=1 bubble_coral=1 bubble_coral_fan=1" +
            "bubble_coral_wall_fan=1 cherry_leaves=1 chorus_flower=1 chorus_plant=1 cobweb=1 conduit=1 cyan_shulker_box=1" +
            "dark_oak_leaves=1 dead_brain_coral=1 dead_brain_coral_fan=1 dead_brain_coral_wall_fan=1 dead_bubble_coral=1" +
            "dead_bubble_coral_fan=1 dead_bubble_coral_wall_fan=1 dead_fire_coral=1 dead_fire_coral_fan=1" +
            "dead_fire_coral_wall_fan=1 dead_horn_coral=1 dead_horn_coral_fan=1 dead_horn_coral_wall_fan=1" +
            "dead_tube_coral=1 dead_tube_coral_fan=1 dead_tube_coral_wall_fan=1 end_gateway=1 fire_coral=1 fire_coral_fan=1" +
            "fire_coral_wall_fan=1 flowering_azalea_leaves=1 frosted_ice=1 gray_shulker_box=1 green_shulker_box=1" +
            "honey_block=1 horn_coral=1 horn_coral_fan=1 horn_coral_wall_fan=1 ice=1 jungle_leaves=1 kelp=1 kelp_plant=1" +
            "lava=1 light_blue_shulker_box=1 light_gray_shulker_box=1 lime_shulker_box=1 magenta_shulker_box=1" +
            "mangrove_leaves=1 mangrove_roots=1 oak_leaves=1 orange_shulker_box=1 pale_oak_leaves=1 pink_shulker_box=1" +
            "powder_snow=1 purple_shulker_box=1 red_shulker_box=1 resin_clump=1 sculk_shrieker=1 sculk_vein=1 sea_pickle=1" +
            "seagrass=1 shulker_box=1 slime_block=1 spawner=1 spruce_leaves=1 tall_seagrass=1 test_instance_block=1" +
            "trial_spawner=1 tube_coral=1 tube_coral_fan=1 tube_coral_wall_fan=1 vault=1 water=1 white_shulker_box=1" +
            "yellow_shulker_box=1";
    private static final String EMISSION_DATA =
            "amethyst_cluster=5 beacon=15 brewing_stand=1 brown_mushroom=1 calibrated_sculk_sensor=1 campfire=15 conduit=15" +
            "copper_lantern=15 copper_torch=14 copper_wall_torch=14 crying_obsidian=10 dragon_egg=1 enchanting_table=7" +
            "end_gateway=15 end_portal=15 end_portal_frame=1 end_rod=14 ender_chest=7 exposed_copper_lantern=15 fire=15" +
            "firefly_bush=2 glowstone=15 jack_o_lantern=15 lantern=15 large_amethyst_bud=4 lava=15 lava_cauldron=15" +
            "light=15 magma_block=3 medium_amethyst_bud=2 nether_portal=11 ochre_froglight=15 oxidized_copper_lantern=15" +
            "pearlescent_froglight=15 redstone_torch=7 redstone_wall_torch=7 sculk_catalyst=6 sculk_sensor=1 sea_lantern=15" +
            "sea_pickle=6 shroomlight=15 small_amethyst_bud=1 soul_campfire=10 soul_fire=10 soul_lantern=10 soul_torch=10" +
            "soul_wall_torch=10 torch=14 vault=6 verdant_froglight=15 wall_torch=14 waxed_copper_lantern=15" +
            "waxed_exposed_copper_lantern=15 waxed_oxidized_copper_lantern=15 waxed_weathered_copper_lantern=15" +
            "weathered_copper_lantern=15";
    private static final String FULL_CUBE_DATA =
            "acacia_log acacia_planks acacia_wood amethyst_block ancient_debris andesite bamboo_block bamboo_mosaic" +
            "bamboo_planks barrel basalt bedrock bee_nest beehive birch_log birch_planks birch_wood black_concrete" +
            "black_concrete_powder black_glazed_terracotta black_terracotta black_wool blackstone blast_furnace" +
            "blue_concrete blue_concrete_powder blue_glazed_terracotta blue_ice blue_terracotta blue_wool bone_block" +
            "bookshelf brain_coral_block bricks brown_concrete brown_concrete_powder brown_glazed_terracotta" +
            "brown_mushroom_block brown_terracotta brown_wool bubble_coral_block budding_amethyst calcite cartography_table" +
            "carved_pumpkin chain_command_block cherry_log cherry_planks cherry_wood chiseled_bookshelf chiseled_copper" +
            "chiseled_deepslate chiseled_nether_bricks chiseled_polished_blackstone chiseled_quartz_block" +
            "chiseled_red_sandstone chiseled_resin_bricks chiseled_sandstone chiseled_stone_bricks chiseled_tuff" +
            "chiseled_tuff_bricks clay coal_block coal_ore coarse_dirt cobbled_deepslate cobblestone command_block" +
            "copper_block copper_bulb copper_ore cracked_deepslate_bricks cracked_deepslate_tiles cracked_nether_bricks" +
            "cracked_polished_blackstone_bricks cracked_stone_bricks crafter crafting_table creaking_heart crimson_hyphae" +
            "crimson_nylium crimson_planks crimson_stem crying_obsidian cut_copper cut_red_sandstone cut_sandstone" +
            "cyan_concrete cyan_concrete_powder cyan_glazed_terracotta cyan_terracotta cyan_wool dark_oak_log" +
            "dark_oak_planks dark_oak_wood dark_prismarine dead_brain_coral_block dead_bubble_coral_block" +
            "dead_fire_coral_block dead_horn_coral_block dead_tube_coral_block deepslate deepslate_bricks" +
            "deepslate_coal_ore deepslate_copper_ore deepslate_diamond_ore deepslate_emerald_ore deepslate_gold_ore" +
            "deepslate_iron_ore deepslate_lapis_ore deepslate_redstone_ore deepslate_tiles diamond_block diamond_ore" +
            "diorite dirt dispenser dried_kelp_block dripstone_block dropper emerald_block emerald_ore end_stone" +
            "end_stone_bricks exposed_chiseled_copper exposed_copper exposed_copper_bulb exposed_cut_copper" +
            "fire_coral_block fletching_table furnace gilded_blackstone glowstone gold_block gold_ore granite grass_block" +
            "gravel gray_concrete gray_concrete_powder gray_glazed_terracotta gray_terracotta gray_wool green_concrete" +
            "green_concrete_powder green_glazed_terracotta green_terracotta green_wool hay_block honeycomb_block" +
            "horn_coral_block infested_chiseled_stone_bricks infested_cobblestone infested_cracked_stone_bricks" +
            "infested_deepslate infested_mossy_stone_bricks infested_stone infested_stone_bricks iron_block iron_ore" +
            "jack_o_lantern jigsaw jukebox jungle_log jungle_planks jungle_wood lapis_block lapis_ore light_blue_concrete" +
            "light_blue_concrete_powder light_blue_glazed_terracotta light_blue_terracotta light_blue_wool" +
            "light_gray_concrete light_gray_concrete_powder light_gray_glazed_terracotta light_gray_terracotta" +
            "light_gray_wool lime_concrete lime_concrete_powder lime_glazed_terracotta lime_terracotta lime_wool lodestone" +
            "loom magenta_concrete magenta_concrete_powder magenta_glazed_terracotta magenta_terracotta magenta_wool" +
            "magma_block mangrove_log mangrove_planks mangrove_wood melon moss_block mossy_cobblestone mossy_stone_bricks" +
            "mud_bricks muddy_mangrove_roots mushroom_stem mycelium nether_bricks nether_gold_ore nether_quartz_ore" +
            "nether_wart_block netherite_block netherrack note_block oak_log oak_planks oak_wood observer obsidian" +
            "ochre_froglight orange_concrete orange_concrete_powder orange_glazed_terracotta orange_terracotta orange_wool" +
            "oxidized_chiseled_copper oxidized_copper oxidized_copper_bulb oxidized_cut_copper packed_ice packed_mud" +
            "pale_moss_block pale_oak_log pale_oak_planks pale_oak_wood pearlescent_froglight pink_concrete" +
            "pink_concrete_powder pink_glazed_terracotta pink_terracotta pink_wool podzol polished_andesite polished_basalt" +
            "polished_blackstone polished_blackstone_bricks polished_deepslate polished_diorite polished_granite" +
            "polished_tuff prismarine prismarine_bricks pumpkin purple_concrete purple_concrete_powder" +
            "purple_glazed_terracotta purple_terracotta purple_wool purpur_block purpur_pillar quartz_block quartz_bricks" +
            "quartz_pillar raw_copper_block raw_gold_block raw_iron_block red_concrete red_concrete_powder" +
            "red_glazed_terracotta red_mushroom_block red_nether_bricks red_sand red_sandstone red_terracotta red_wool" +
            "redstone_block redstone_lamp redstone_ore reinforced_deepslate repeating_command_block resin_block" +
            "resin_bricks respawn_anchor rooted_dirt sand sandstone sculk sculk_catalyst sea_lantern shroomlight" +
            "smithing_table smoker smooth_basalt smooth_quartz smooth_red_sandstone smooth_sandstone smooth_stone" +
            "snow_block soul_soil sponge spruce_log spruce_planks spruce_wood stone stone_bricks stripped_acacia_log" +
            "stripped_acacia_wood stripped_bamboo_block stripped_birch_log stripped_birch_wood stripped_cherry_log" +
            "stripped_cherry_wood stripped_crimson_hyphae stripped_crimson_stem stripped_dark_oak_log" +
            "stripped_dark_oak_wood stripped_jungle_log stripped_jungle_wood stripped_mangrove_log stripped_mangrove_wood" +
            "stripped_oak_log stripped_oak_wood stripped_pale_oak_log stripped_pale_oak_wood stripped_spruce_log" +
            "stripped_spruce_wood stripped_warped_hyphae stripped_warped_stem structure_block suspicious_gravel" +
            "suspicious_sand target terracotta test_block tinted_glass tnt tube_coral_block tuff tuff_bricks" +
            "verdant_froglight warped_hyphae warped_nylium warped_planks warped_stem warped_wart_block" +
            "waxed_chiseled_copper waxed_copper_block waxed_copper_bulb waxed_cut_copper waxed_exposed_chiseled_copper" +
            "waxed_exposed_copper waxed_exposed_copper_bulb waxed_exposed_cut_copper waxed_oxidized_chiseled_copper" +
            "waxed_oxidized_copper waxed_oxidized_copper_bulb waxed_oxidized_cut_copper waxed_weathered_chiseled_copper" +
            "waxed_weathered_copper waxed_weathered_copper_bulb waxed_weathered_cut_copper weathered_chiseled_copper" +
            "weathered_copper weathered_copper_bulb weathered_cut_copper wet_sponge white_concrete white_concrete_powder" +
            "white_glazed_terracotta white_terracotta white_wool yellow_concrete yellow_concrete_powder" +
            "yellow_glazed_terracotta yellow_terracotta yellow_wool";

    private static final Set<String> ZERO_FILTER = parseSet(ZERO_FILTER_DATA);
    private static final Map<String, Integer> PARTIAL_FILTER = parseMap(PARTIAL_FILTER_DATA);
    private static final Map<String, Integer> EMISSION = parseMap(EMISSION_DATA);
    private static final Set<String> FULL_CUBE = parseSet(FULL_CUBE_DATA);

    private BridgeBlockRenderingData() {
    }

    static int filterLight(final String identifier) {
        if (ZERO_FILTER.contains(identifier)) return 0;
        return PARTIAL_FILTER.getOrDefault(identifier, 15);
    }

    static int emission(final String identifier) {
        return EMISSION.getOrDefault(identifier, 0);
    }

    static boolean isSolidFullCube(final String identifier) {
        return FULL_CUBE.contains(identifier);
    }

    private static Set<String> parseSet(final String data) {
        if (data.isEmpty()) return Set.of();
        return Set.copyOf(Arrays.asList(data.split(" ")));
    }

    private static Map<String, Integer> parseMap(final String data) {
        final Map<String, Integer> result = new HashMap<>();
        if (data.isEmpty()) return result;

        for (String entry : data.split(" ")) {
            final int separator = entry.lastIndexOf('=');
            result.put(entry.substring(0, separator), Integer.parseInt(entry.substring(separator + 1)));
        }
        return Map.copyOf(result);
    }

}
