package net.raphimc.viabedrock.api.model.container;

import java.util.Set;

/**
 * Vanilla Java 26.1 furnace fuels generated by Geyser's mapping generator from
 * Mojang FuelValues.vanillaBurnTimes for the Bedrock 1.26.50 mapping set.
 */
public final class BridgeFurnaceFuelData {
    private static final Set<String> IDENTIFIERS = Set.of(("""
            minecraft:acacia_boat minecraft:acacia_button minecraft:acacia_chest_boat minecraft:acacia_door minecraft:acacia_fence
            minecraft:acacia_fence_gate minecraft:acacia_hanging_sign minecraft:acacia_log minecraft:acacia_planks minecraft:acacia_pressure_plate
            minecraft:acacia_sapling minecraft:acacia_shelf minecraft:acacia_sign minecraft:acacia_slab minecraft:acacia_stairs
            minecraft:acacia_trapdoor minecraft:acacia_wood minecraft:azalea minecraft:bamboo minecraft:bamboo_block
            minecraft:bamboo_button minecraft:bamboo_chest_raft minecraft:bamboo_door minecraft:bamboo_fence minecraft:bamboo_fence_gate
            minecraft:bamboo_hanging_sign minecraft:bamboo_mosaic minecraft:bamboo_mosaic_slab minecraft:bamboo_mosaic_stairs minecraft:bamboo_planks
            minecraft:bamboo_pressure_plate minecraft:bamboo_raft minecraft:bamboo_shelf minecraft:bamboo_sign minecraft:bamboo_slab
            minecraft:bamboo_stairs minecraft:bamboo_trapdoor minecraft:barrel minecraft:birch_boat minecraft:birch_button
            minecraft:birch_chest_boat minecraft:birch_door minecraft:birch_fence minecraft:birch_fence_gate minecraft:birch_hanging_sign
            minecraft:birch_log minecraft:birch_planks minecraft:birch_pressure_plate minecraft:birch_sapling minecraft:birch_shelf
            minecraft:birch_sign minecraft:birch_slab minecraft:birch_stairs minecraft:birch_trapdoor minecraft:birch_wood
            minecraft:black_banner minecraft:black_carpet minecraft:black_wool minecraft:blaze_rod minecraft:blue_banner
            minecraft:blue_carpet minecraft:blue_wool minecraft:bookshelf minecraft:bow minecraft:bowl
            minecraft:brown_banner minecraft:brown_carpet minecraft:brown_wool minecraft:cartography_table minecraft:charcoal
            minecraft:cherry_boat minecraft:cherry_button minecraft:cherry_chest_boat minecraft:cherry_door minecraft:cherry_fence
            minecraft:cherry_fence_gate minecraft:cherry_hanging_sign minecraft:cherry_log minecraft:cherry_planks minecraft:cherry_pressure_plate
            minecraft:cherry_sapling minecraft:cherry_shelf minecraft:cherry_sign minecraft:cherry_slab minecraft:cherry_stairs
            minecraft:cherry_trapdoor minecraft:cherry_wood minecraft:chest minecraft:chiseled_bookshelf minecraft:coal
            minecraft:coal_block minecraft:composter minecraft:crafting_table minecraft:crossbow minecraft:cyan_banner
            minecraft:cyan_carpet minecraft:cyan_wool minecraft:dark_oak_boat minecraft:dark_oak_button minecraft:dark_oak_chest_boat
            minecraft:dark_oak_door minecraft:dark_oak_fence minecraft:dark_oak_fence_gate minecraft:dark_oak_hanging_sign minecraft:dark_oak_log
            minecraft:dark_oak_planks minecraft:dark_oak_pressure_plate minecraft:dark_oak_sapling minecraft:dark_oak_shelf minecraft:dark_oak_sign
            minecraft:dark_oak_slab minecraft:dark_oak_stairs minecraft:dark_oak_trapdoor minecraft:dark_oak_wood minecraft:daylight_detector
            minecraft:dead_bush minecraft:dried_kelp_block minecraft:fishing_rod minecraft:fletching_table minecraft:flowering_azalea
            minecraft:gray_banner minecraft:gray_carpet minecraft:gray_wool minecraft:green_banner minecraft:green_carpet
            minecraft:green_wool minecraft:jukebox minecraft:jungle_boat minecraft:jungle_button minecraft:jungle_chest_boat
            minecraft:jungle_door minecraft:jungle_fence minecraft:jungle_fence_gate minecraft:jungle_hanging_sign minecraft:jungle_log
            minecraft:jungle_planks minecraft:jungle_pressure_plate minecraft:jungle_sapling minecraft:jungle_shelf minecraft:jungle_sign
            minecraft:jungle_slab minecraft:jungle_stairs minecraft:jungle_trapdoor minecraft:jungle_wood minecraft:ladder
            minecraft:lava_bucket minecraft:leaf_litter minecraft:lectern minecraft:light_blue_banner minecraft:light_blue_carpet
            minecraft:light_blue_wool minecraft:light_gray_banner minecraft:light_gray_carpet minecraft:light_gray_wool minecraft:lime_banner
            minecraft:lime_carpet minecraft:lime_wool minecraft:loom minecraft:magenta_banner minecraft:magenta_carpet
            minecraft:magenta_wool minecraft:mangrove_boat minecraft:mangrove_button minecraft:mangrove_chest_boat minecraft:mangrove_door
            minecraft:mangrove_fence minecraft:mangrove_fence_gate minecraft:mangrove_hanging_sign minecraft:mangrove_log minecraft:mangrove_planks
            minecraft:mangrove_pressure_plate minecraft:mangrove_propagule minecraft:mangrove_roots minecraft:mangrove_shelf minecraft:mangrove_sign
            minecraft:mangrove_slab minecraft:mangrove_stairs minecraft:mangrove_trapdoor minecraft:mangrove_wood minecraft:note_block
            minecraft:oak_boat minecraft:oak_button minecraft:oak_chest_boat minecraft:oak_door minecraft:oak_fence
            minecraft:oak_fence_gate minecraft:oak_hanging_sign minecraft:oak_log minecraft:oak_planks minecraft:oak_pressure_plate
            minecraft:oak_sapling minecraft:oak_shelf minecraft:oak_sign minecraft:oak_slab minecraft:oak_stairs
            minecraft:oak_trapdoor minecraft:oak_wood minecraft:orange_banner minecraft:orange_carpet minecraft:orange_wool
            minecraft:pale_oak_boat minecraft:pale_oak_button minecraft:pale_oak_chest_boat minecraft:pale_oak_door minecraft:pale_oak_fence
            minecraft:pale_oak_fence_gate minecraft:pale_oak_hanging_sign minecraft:pale_oak_log minecraft:pale_oak_planks minecraft:pale_oak_pressure_plate
            minecraft:pale_oak_sapling minecraft:pale_oak_shelf minecraft:pale_oak_sign minecraft:pale_oak_slab minecraft:pale_oak_stairs
            minecraft:pale_oak_trapdoor minecraft:pale_oak_wood minecraft:pink_banner minecraft:pink_carpet minecraft:pink_wool
            minecraft:purple_banner minecraft:purple_carpet minecraft:purple_wool minecraft:red_banner minecraft:red_carpet
            minecraft:red_wool minecraft:scaffolding minecraft:short_dry_grass minecraft:smithing_table minecraft:spruce_boat
            minecraft:spruce_button minecraft:spruce_chest_boat minecraft:spruce_door minecraft:spruce_fence minecraft:spruce_fence_gate
            minecraft:spruce_hanging_sign minecraft:spruce_log minecraft:spruce_planks minecraft:spruce_pressure_plate minecraft:spruce_sapling
            minecraft:spruce_shelf minecraft:spruce_sign minecraft:spruce_slab minecraft:spruce_stairs minecraft:spruce_trapdoor
            minecraft:spruce_wood minecraft:stick minecraft:stripped_acacia_log minecraft:stripped_acacia_wood minecraft:stripped_bamboo_block
            minecraft:stripped_birch_log minecraft:stripped_birch_wood minecraft:stripped_cherry_log minecraft:stripped_cherry_wood minecraft:stripped_dark_oak_log
            minecraft:stripped_dark_oak_wood minecraft:stripped_jungle_log minecraft:stripped_jungle_wood minecraft:stripped_mangrove_log minecraft:stripped_mangrove_wood
            minecraft:stripped_oak_log minecraft:stripped_oak_wood minecraft:stripped_pale_oak_log minecraft:stripped_pale_oak_wood minecraft:stripped_spruce_log
            minecraft:stripped_spruce_wood minecraft:tall_dry_grass minecraft:trapped_chest minecraft:white_banner minecraft:white_carpet
            minecraft:white_wool minecraft:wooden_axe minecraft:wooden_hoe minecraft:wooden_pickaxe minecraft:wooden_shovel
            minecraft:wooden_spear minecraft:wooden_sword minecraft:yellow_banner minecraft:yellow_carpet minecraft:yellow_wool
            """).strip().split("\\s+"));

    private BridgeFurnaceFuelData() {
    }

    public static boolean isFuel(String identifier) {
        if (identifier == null || identifier.isEmpty()) return false;
        String canonical = identifier.indexOf(':') >= 0 ? identifier : "minecraft:" + identifier;
        return IDENTIFIERS.contains(canonical);
    }

    public static int size() {
        return IDENTIFIERS.size();
    }
}
