'use strict'

const fs = require('fs')
const path = require('path')
const { spawn } = require('child_process')
const { startLanAnnouncer } = require('./javaLanStatusServer')
const { ensureViaProxyInventoryPatch, shouldPatchViaProxyInventory } = require('./viaProxyInventoryPatch')

function normalizeBindHost (host) {
  return host || '0.0.0.0'
}

function normalizeBackendHost (host) {
  if (!host || host === '0.0.0.0' || host === '::') return '127.0.0.1'
  return host
}

function address (host, port) {
  return `${host}:${port}`
}

function upsertSimpleYamlBoolean (content, key, value) {
  const line = `${key}: ${value ? 'true' : 'false'}`
  const pattern = new RegExp(`^${key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}:\\s*(?:true|false)\\s*$`, 'm')
  if (pattern.test(content)) return content.replace(pattern, line)
  return `${line}\n${content || ''}`
}

function boolEnvOrOption (options, optionName, envName, fallback = false) {
  if (options[optionName] === true) return true
  if (options[optionName] === false) return false
  const raw = process.env[envName]
  if (raw == null || raw === '') return fallback
  return ['1', 'true', 'yes', 'y', 'on'].includes(String(raw).trim().toLowerCase())
}

function ensureViaBedrockRelayConfig (config, options = {}) {
  if (options.enableViaBedrockExperimentalFeatures !== true) return undefined

  const runDir = config.javaLan.viaProxyRunDir
  fs.mkdirSync(runDir, { recursive: true })
  const runConfigPath = path.join(runDir, 'viabedrock.yml')
  const rootConfigPath = path.resolve(__dirname, '..', 'viabedrock.yml')

  let content = ''
  if (fs.existsSync(runConfigPath)) {
    content = fs.readFileSync(runConfigPath, 'utf8')
  } else if (fs.existsSync(rootConfigPath)) {
    content = fs.readFileSync(rootConfigPath, 'utf8')
  } else {
    content = '# Generated by JavaRock for ViaBedrock relay mode\n'
  }

  const before = content
  const translateResourcePacks = boolEnvOrOption(
    options,
    'translateViaBedrockResourcePacks',
    'NETHERNET_RELAY_TRANSLATE_RESOURCE_PACKS',
    false
  )
  content = upsertSimpleYamlBoolean(content, 'enable-experimental-features', true)
  content = upsertSimpleYamlBoolean(content, 'translate-resource-packs', translateResourcePacks)

  if (content !== before || !fs.existsSync(runConfigPath)) {
    fs.writeFileSync(runConfigPath, content)
    console.log(`[java-compat] Patched ${runConfigPath}: ViaBedrock experimental features enabled; resource-pack translation ${translateResourcePacks ? 'enabled' : 'disabled'} for relay mode.`)
  } else {
    console.log(`[java-compat] ViaBedrock relay config already matches relay mode: experimental features enabled, resource-pack translation ${translateResourcePacks ? 'enabled' : 'disabled'} (${runConfigPath})`)
  }

  return runConfigPath
}

function normalizeViaProxyTargetVersion (targetVersion) {
  const value = String(targetVersion || '').trim()

  // The local ViaBedrock front door is pinned to the Bedrock packet schema
  // that this bridge normalizes toward. Passing the upstream Realm version here
  // makes ViaProxy fall back to auto detection, which can fail against our local
  // relay before the bridge ever gets a downstream session.
  if (/^bedrock\s+1\.26\.(?:10|20)$/i.test(value)) {
    console.warn(`[java-compat] ViaProxy target "${value}" is not supported by the current ViaProxy jar. Using "Bedrock 1.26.30" for the ViaBedrock front door.`)
    return 'Bedrock 1.26.30'
  }

  return value || '1.21.11'
}

function findViaProxyJar (config) {
  const candidates = []
  if (config.javaLan.viaProxyJar) candidates.push(config.javaLan.viaProxyJar)

  const root = path.resolve(__dirname, '..')
  candidates.push(
    path.join(root, 'tools', 'ViaProxy.jar'),
    path.join(root, 'ViaProxy.jar')
  )

  for (const dir of [
    path.join(root, '.vendor', 'ViaProxy', 'build', 'libs'),
    path.join(root, 'tools')
  ]) {
    try {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        if (entry.isFile() && /^viaproxy.*\.jar$/i.test(entry.name)) {
          candidates.push(path.join(dir, entry.name))
        }
      }
    } catch {}
  }

  return candidates.find(candidate => {
    try {
      return fs.statSync(candidate).isFile()
    } catch {
      return false
    }
  })
}

function buildViaProxyCommand (config, backendConfig, jarPath, options = {}) {
  const bindAddress = address(normalizeBindHost(config.javaLan.host), config.javaLan.port)
  const targetAddress = options.targetAddress || address(normalizeBackendHost(backendConfig.javaLan.host), backendConfig.javaLan.port)
  const requestedTargetVersion = options.targetVersion || config.javaLan.viaProxyTargetVersion || backendConfig.javaLan.playVersion || '1.21.11'
  const targetVersion = normalizeViaProxyTargetVersion(requestedTargetVersion)

  return {
    executable: 'java',
    args: [
      '-DskipUpdateCheck=true',
      '-DignoreSystemRequirements=true',
      '-jar',
      jarPath,
      'cli',
      '--bind-address',
      bindAddress,
      '--target-address',
      targetAddress,
      '--target-version',
      targetVersion,
      '--auth-method',
      'NONE',
      '--proxy-online-mode',
      'false',
      '--custom-motd',
      config.javaLan.motd || 'JavaRock'
    ],
    bindAddress,
    targetAddress,
    targetVersion
  }
}

function startJavaCompatProxy (config, backendConfig, options = {}) {
  const mode = (config.javaLan.compatMode || 'direct').toLowerCase()
  if (mode !== 'viaproxy') {
    return {
      mode: 'direct',
      available: true,
      close () {}
    }
  }

  const jarPath = findViaProxyJar(config)
  if (!jarPath) {
    console.warn('[java-compat] ViaProxy compatibility mode requested, but no ViaProxy jar was found.')
    console.warn('[java-compat] Run .\\install-viaproxy.ps1, put ViaProxy.jar at tools\\ViaProxy.jar, or pass --viaproxy-jar <path-to-jar>.')
    console.warn('[java-compat] A stock/latest Java client will not reach localhost:25565 until the ViaProxy front door is installed.')
    console.warn(`[java-compat] Local relay target: ${backendConfig.javaLan.host}:${backendConfig.javaLan.port}.`)
    return {
      mode: 'viaproxy',
      available: false,
      close () {}
    }
  }

  fs.mkdirSync(config.javaLan.viaProxyRunDir, { recursive: true })
  const effectiveJarPath = shouldPatchViaProxyInventory()
    ? ensureViaProxyInventoryPatch(jarPath, config.javaLan.viaProxyRunDir)
    : jarPath
  const command = buildViaProxyCommand(config, backendConfig, effectiveJarPath, options)
  const targetLabel = options.targetLabel || 'local relay target'

  console.log('[java-compat] Starting ViaProxy compatibility front door:')
  console.log(`[java-compat] Java client connects to ${command.bindAddress}`)
  console.log(`[java-compat] ViaProxy forwards to ${targetLabel} ${command.targetAddress} as ${command.targetVersion}`)
  const viaBedrockConfigPath = ensureViaBedrockRelayConfig(config, options)
  if (viaBedrockConfigPath) console.log(`[java-compat] ViaBedrock config: ${viaBedrockConfigPath}`)

  if (options.dryRun) {
    return {
      mode: 'viaproxy',
      available: true,
      command,
      viaBedrockConfigPath,
      close () {}
    }
  }

  const child = spawn(command.executable, command.args, {
    cwd: config.javaLan.viaProxyRunDir,
    env: {
      ...process.env,
      VP_RUN_DIR: config.javaLan.viaProxyRunDir
    },
    stdio: 'inherit',
    windowsHide: true
  })

  const announcer = options.announceLan
    ? startLanAnnouncer({
      motd: options.lanMotd || config.javaLan.motd || 'JavaRock',
        port: config.javaLan.port
      })
    : undefined

  if (announcer) {
    console.log(`[java-compat] Advertising ViaProxy public port as a Java LAN server on port ${config.javaLan.port}.`)
  }

  child.on('exit', (code, signal) => {
    const reason = signal || code
    console.log(`[java-compat] ViaProxy exited: ${reason}`)
  })

  child.on('error', error => {
    console.error(`[java-compat] Failed to start ViaProxy: ${error.stack || error.message || error}`)
  })

  const close = () => {
    announcer?.close()
    if (!child.killed) child.kill()
  }

  process.once('SIGINT', close)
  process.once('SIGTERM', close)

  return {
    mode: 'viaproxy',
    available: true,
    lanAdvertised: Boolean(announcer),
    lanAnnouncePort: announcer ? config.javaLan.port : undefined,
    child,
    command,
    viaBedrockConfigPath,
    close
  }
}

function printJavaCompatProxyInfo (config) {
  const relayHost = config.bedrockRelay?.host || '127.0.0.1'
  const relayPort = config.bedrockRelay?.port || 19133
  const targetVersion = config.bedrockRelay?.viaProxyTargetVersion || config.javaLan.viaProxyBedrockTargetVersion || 'Bedrock 1.26.30'
  const backendConfig = {
    ...config,
    javaLan: {
      ...config.javaLan,
      host: relayHost,
      port: relayPort,
      playVersion: targetVersion
    }
  }
  const jarPath = findViaProxyJar(config)
  const command = buildViaProxyCommand(config, backendConfig, jarPath || '<path-to-ViaProxy.jar>', {
    targetAddress: address(relayHost, relayPort),
    targetVersion
  })

  console.log('[java-compat] ViaProxy compatibility plan:')
  console.log(`  mode: ${config.javaLan.compatMode || 'direct'}`)
  console.log(`  jar found: ${jarPath ? 'yes' : 'no'}`)
  console.log(`  jar path: ${jarPath || config.javaLan.viaProxyJar || 'tools\\\\ViaProxy.jar'}`)
  console.log(`  Java client connects to: ${command.bindAddress}`)
  console.log(`  Local Bedrock relay: ${command.targetAddress}`)
  console.log(`  ViaProxy target version: ${command.targetVersion}`)
  console.log(`  command: ${command.executable} ${command.args.map(arg => /\s/.test(arg) ? `"${arg}"` : arg).join(' ')}`)

  if (!jarPath) {
    console.log('[java-compat] Run .\\install-viaproxy.ps1, put ViaProxy.jar at tools\\ViaProxy.jar, or pass --viaproxy-jar <path-to-jar>.')
  }
}

module.exports = {
  buildViaProxyCommand,
  ensureViaBedrockRelayConfig,
  normalizeViaProxyTargetVersion,
  findViaProxyJar,
  printJavaCompatProxyInfo,
  startJavaCompatProxy
}
